---

- assert:
    that:
      - ansible_ssh_user != 'root'
      - ansible_user_dir is defined

- name: our dot dir
  file: { path: '{{ dir }}', state: directory }

- name: generate crypted password
  command: mkpasswd {{ screen_password }} {{ salt }}
  register: mkpasswd
  no_log: True
  check_mode: False
  changed_when: False
  when: &passwd screen_password is defined and screen_password != ''
  delegate_to: localhost

- set_fact:
    crypted_screen_password: |-
      {{ mkpasswd.stdout }}
  when: *passwd
    
- name: generate file
  with_items: files
  template:
    src: '{{ name }}.j2'
    dest: &dest '{{ dir }}/{{ group | default(name) }}.screen'

- { name: runp, register: runp, changed_when: False, command: date }

- name: link to file
  when: not runp | skipped
  file:
    state: link
    src: *dest
    dest: |-
      ~/{{ link | default('.screenrc-' + group | default(name)) }}
